stages:
  - continuose-intgeration
  

frontend-integration-test:
  stage: continuose-intgeration
  image: node  
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false

frontend-lint:
  stage: continuose-intgeration
  image: node
  script:
    - npm install
    - npm run lint